export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-gray-900 mb-6">Terms of Service</h1>
      <div className="prose prose-gray max-w-none space-y-4 text-gray-600 leading-relaxed text-sm">
        <p><em>Last updated: August 27, 2026</em></p>
        <p>
          Welcome to AnyTool.site. By accessing or using our website, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use our website.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">Use of Tools</h2>
        <p>
          All tools provided on AnyTool.site are free to use. You may use them for personal or commercial purposes. We do not guarantee the accuracy or completeness of any output generated by our tools.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">Intellectual Property</h2>
        <p>
          The content, design, and code of AnyTool.site are owned by us and protected by copyright laws. You may not reproduce, distribute, or create derivative works without our written permission.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">User Conduct</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Use our tools for any illegal purpose</li>
          <li>Attempt to disrupt or overload our servers</li>
          <li>Scrape or automatedly collect content from our site</li>
          <li>Imply any form of association or endorsement without permission</li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">Disclaimer</h2>
        <p>
          Our tools are provided "as is" without warranties of any kind. We are not liable for any damages arising from the use of our tools or website.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. Continued use of the site after changes constitutes acceptance of the new terms.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">Contact</h2>
        <p>
          For questions about these Terms, please visit our <a href="/contact" className="text-indigo-600 hover:underline">Contact page</a>.
        </p>
      </div>
    </div>
  )
}
